### ISSUE TITLE
MELDA GUI problems on Reaper

### ISSUE THREAD

**Issue by ghost** [osxmidi/LinVst3#1]
LinVst3 v.1.66, Reaper 5.983, Melda 13.05, Linux Mint 19.03_x64 Cinnamom

Hi, 

Thanks for your great work!!!

I warn you that when I try to resize the GUI of the plug-ins in Reaper (Latest version of Linux), the GUI is sized correctly, but not the size of the plug-in window and you can't work

**Comment by osxmidi** [comment]
It's done that way for DAW compatibility reasons, because some DAWs might have trouble with window size updates, so it needs to be done manually.

After a window resize, just close the vst window and then reopen the window and it should be the right size.

**Comment by ghost** [comment]
Hi,

many thanks.... it works! Now I try other .vst3 plugins... 
many thanks for LinVST and LinVST3!!!!

PS: 
the file selection operation is not user frendly.... For example:
1. If the files .vst3 are cataloged in some sub-directory, I need to  generate the .so file for each sub-directory. It's possible to select only the root of .vst3 files and then generate the .so for each?
2. I need to select the .so3 file for each .vst3 new directory: but the link to this file remain this for all the operation. It's possible to link only one time the .so3 file?

Thanks again....
