### ISSUE TITLE
invalid ELF header errors in Reaper

### ISSUE THREAD

**Issue by Centrifium** [osxmidi/LinVst3#13]
I get this in reapers term on startup

swell: dlopen() failed: /home/kaden/.wine/drive_c/Program Files/Common Files/VST3/ValhallaSupermassive.vst3: invalid ELF header
swell: dlopen() failed: /home/kaden/.wine/drive_c/Program Files/Common Files/VST3/LABS (64 Bit).vst3: invalid ELF header
swell: dlopen() failed: /home/kaden/.wine/drive_c/Program Files/Common Files/VST3/ValhallaSupermassive.vst3: invalid ELF header
swell: dlopen() failed: /home/kaden/.wine/drive_c/Program Files/Common Files/VST3/LABS (64 Bit).vst3: invalid ELF header
swell: dlopen() failed: /home/kaden/.wine/drive_c/Program Files/Common Files/VST3/LABS (64 Bit).vst3: invalid ELF header
swell: dlopen() failed: /home/kaden/.wine/drive_c/Program Files/Common Files/VST3/LABS (64 Bit).vst3: invalid ELF header

**Comment by Centrifium** [comment]
Another thing to note, Reaper fails to scan every single vst3 on my system along with every linux vst, so I could just have an incredibly broken reaper install.

**Comment by osxmidi** [comment]
>  invalid ELF header

The  invalid ELF header output is just Linux Reaper having a look at a Windows vst3 and deciding it's not a Linux vst3, in other words it's nothing to be concerned about it's just that Linux Reaper can not load Windows vst/vst's directly.

The scanning needs a matched .so file for the vst/vst3 Windows file (done using  linvst3convert).

If for example there is a Windows vst3 file called delay.vst3 then there should be a delay.so file right next to the delay.vst3 file as well.

 Reaper loads the Linux delay.so file which then loads the Windows delay.vst3 file.

**Comment by Centrifium** [comment]
Ah I see, so the ELF header has nothing to do with my real problem, reaper is unable to scan vst3's
