### ISSUE TITLE
Only first plugin is detected per waves vst3 file

### ISSUE THREAD

**Issue by niculw** [osxmidi/LinVst3#14]
Using LinVst3-4.5 it seem that only the first VST3 of each bundle is detected. An old version, i.e. linvst3-2.1 finds only the first one on the first pass but then created a lot of "part" files that would then find every plugin.

**Comment by osxmidi** [comment]
> Using LinVst3-4.5 it seem that only the first VST3 of each bundle is detected. An old version, i.e. linvst3-2.1 finds only the first one on the first pass but then created a lot of "part" files that would then find every plugin.

Yes, it created part files.

I did change some of the code to handle the newer vst3 plugin folder format (instead of just a vst3 file) and something must have happened when I did that.

I'll look into it.

**Comment by osxmidi** [comment]
> Using LinVst3-4.5 it seem that only the first VST3 of each bundle is detected. An old version, i.e. linvst3-2.1 finds only the first one on the first pass but then created a lot of "part" files that would then find every plugin.

I found the problem and I have updated  LinVst3-4.5.2-Manjaro.zip on the releases page.
