### ISSUE TITLE
Reason Rack VST3 only Instrument plugin shows in DAW - Reason Rack Effects rack is missing

### ISSUE THREAD

**Issue by atomik4** [osxmidi/LinVst3#16]
Using:

wine-6.14 (Staging)
LinVst3-4.5.2-Manjaro
Renoise 3.3.2 Linux-x64
Reason_1139_d22-Stable-184-Win
Manjaro based all updates except kernel 5.10.59-rt51-xanmod1-1.51

Upon setting-up the VST3 path and having used linvst3convert, upon scanning for new plugins in Renoise does reveal
"Reason Rack Plugin" is listed in the "Instruments" section, but there is no Reason Studios plugin listed in the "Effects" area.
A bit disappointed because everything about the Reason Instrument seems to work!

One thing I am unsure of is filesystem layout for the VST3 .so file. After running the linvst3convert it creates  ~/.wine/drive_c/Program Files/Common Files/VST3/Reason Rack Plugin.vst3/Contents/x86_64-win/Reason Rack Plugin.so
Then after you open the Reason plugin in Renoise, a file gets created: ~/.wine/drive_c/Program Files/Common Files/VST3/Reason Rack Plugin-part-01.so - which is an empty 0k file.

So maybe this is a Renoise quirk? Or is it a linvst3 issue?

Update: I tested on Bitwig Studio 2.5.1, and only the instrument version of Reason Rack Plugin is available - there's no effects version.

-----
There's another issue - rack effect validation is broken. You can update all the racks in the reason+ app, but everytime you start the rack plugin or reason itself you receive a prompt to authorize the rack effects. This may need some hacking to find out what the reason+ app is trying to communicate with the main reason app, because even if you manually open both apps and what appears to be a successful validation - none of the extra reason+ rack effects are registered with reason/reason rack plugin.

I would rather time be spent on getting the Reason Rack as an effect plugin working, because 1)Guessing easier to fix, and 2)It's a huge chunk of functionality.

**Comment by osxmidi** [comment]
> Using:
> 
> wine-6.14 (Staging)
> LinVst3-4.5.2-Manjaro
> Renoise 3.3.2 Linux-x64
> Reason_1139_d22-Stable-184-Win
> Manjaro based all updates except kernel 5.10.59-rt51-xanmod1-1.51
> 
> Upon setting-up the VST3 path and having used linvst3convert, upon scanning for new plugins in Renoise does reveal
> "Reason Rack Plugin" is listed in the "Instruments" section, but there is no Reason Studios plugin listed in the "Effects" area.
> A bit disappointed because everything about the Reason Instrument seems to work!
> 
> One thing I am unsure of is filesystem layout for the VST3 .so file. After running the linvst3convert it creates ~/.wine/drive_c/Program Files/Common Files/VST3/Reason Rack Plugin.vst3/Contents/x86_64-win/Reason Rack Plugin.so
> Then after you open the Reason plugin in Renoise, a file gets created: ~/.wine/drive_c/Program Files/Common Files/VST3/Reason Rack Plugin-part-01.so - which is an empty 0k file.
> 
> So maybe this is a Renoise quirk? Or is it a linvst3 issue?
> 
> Update: I tested on Bitwig Studio 2.5.1, and only the instrument version of Reason Rack Plugin is available - there's no effects version.
> 
> There's another issue - rack effect validation is broken. You can update all the racks in the reason+ app, but everytime you start the rack plugin or reason itself you receive a prompt to authorize the rack effects. This may need some hacking to find out what the reason+ app is trying to communicate with the main reason app, because even if you manually open both apps and what appears to be a successful validation - none of the extra reason+ rack effects are registered with reason/reason rack plugin.
> 
> I would rather time be spent on getting the Reason Rack as an effect plugin working, because 1)Guessing easier to fix, and 2)It's a huge chunk of functionality.

The Reason Rack Plugin-part-01.so file means that the vst3 was a multi part vst3 dll and it contained more than 1 plugin, probably the instrument and effect plugins.

It's not supposed to be 0 kb, it's supposed to be the same size as lintvst3.so is, so something is going wrong there.

When the vst3 plugin is first loaded, if it's a multiple plugin vst3 then other parts (like the Reason Rack Plugin-part-01.so file) are created to match the multiple plugins in the vst3.

Then on the next Daw start, all of the vst3 parts will be loaded resulting in (the vst3's) multiple plugins available within the Daw.

Multi part vst3's are sometimes used by some plugin makers such as Waves for instance.

LinVst3 has been tested with Waves and the multi part (-part-01.so etc files) do work.

Why your Reason Rack Plugin-part-01.so file is 0 kb, I don't know, it shouldn't be 0 kb.

One way might be to use a copy of linvst3.so and rename it to Reason Rack Plugin-part-01.so and then move/overwrite it to where the Reason Rack Plugin-part-01.so file is.

**Comment by osxmidi** [comment]
Authentication probably depends on the winbind and libntlm0 and gnutls packages.

lib32-gnutls and winbindd on Arch.

**Comment by atomik4** [comment]
I tried renaming linvst3.so, but that didn't work (just showed as another instrument plugin, but broken when launched).
There is the 'main' dll plugin inside the vst3 bundle, and there is a .so file made by linvst3convert. It doesn't seem to be successful at making separate .so files so not sure what to do there.

On the license issue, of course I do have samba and gnutls and a few other installed - it's not that Reason won't authorize via web login (it does) - it won't update the licenses for the rack effects (reason + has all of the rack effects), and so it's using just the builtin plugins.

**Comment by osxmidi** [comment]
I can't get Reason to install.

I suspect that Wine can't handle what Reason is doing.

**Comment by atomik4** [comment]
Try Reason 11 and wine set at Windows 7.
Reason 12 requires Windows 10 and doesn't work so great with wine.

**Comment by osxmidi** [comment]
> Try Reason 11 and wine set at Windows 7.
> Reason 12 requires Windows 10 and doesn't work so great with wine.

I tried installing Reason+ and it fails on my system.

I've read that even if Reason appears to work with Wine, there are still problems with things like file selection etc.

**Comment by atomik4** [comment]
My motive was not to use the DAW, but I wanted Reason as a VST.

That's strange it wouldn't install. I don't think it required any kind of intervention on my part.
I know that Reason as a DAW is pretty gimped on Linux - thinks like needing to type alt and then use the keyboard arrow keys to navigate the menus.

I think I installed Reason 11 first, then launched it and deselected auto run of reason + companion app.
Then I installed Reason + and synced all the Reason + Rack Extensions.
I don't use DLL overrides or copied Windows DLLs.

Wine seems to be a moving target these days. I could have used wine-staging 5.12 or 6.16 to install it and then just swapped back to 6.14. Native Instruments used to install with 5.12, but now the latest version (I hate autoupdate) requires the latest wine-staging to be installed. So you have to swap-out the different Wine versions.

Anyway thanks for your time and efforts!
Your projects rock!

**Comment by osxmidi** [comment]
> My motive was not to use the DAW, but I wanted Reason as a VST.
> 
> That's strange it wouldn't install. I don't think it required any kind of intervention on my part.
> I know that Reason as a DAW is pretty gimped on Linux - thinks like needing to type alt and then use the keyboard arrow keys to navigate the menus.
> 
> I think I installed Reason 11 first, then launched it and deselected auto run of reason + companion app.
> Then I installed Reason + and synced all the Reason + Rack Extensions.
> I don't use DLL overrides or copied Windows DLLs.
> 
> Wine seems to be a moving target these days. I could have used wine-staging 5.12 or 6.16 to install it and then just swapped back to 6.14. Native Instruments used to install with 5.12, but now the latest version (I hate autoupdate) requires the latest wine-staging to be installed. So you have to swap-out the different Wine versions.
> 
> Anyway thanks for your time and efforts!
> Your projects rock!

Thanks.
