### ISSUE TITLE
I can't compile linvst3

### ISSUE THREAD

**Issue by ghost** [osxmidi/LinVst3#17]
Running make results in this: 

> ./lin-patchwin
> sed: couldn't open temporary file ../LinVst/sedHTLR6T: Permission denied
> sed: couldn't open temporary file ../LinVst/sedwQm8Xu: Permission denied
> sed: can't read ../public.sdk/source/common/systemclipboard_win32.cpp: No such file or directory
> sed: can't read ../pluginterfaces/base/fplatform.h: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/fstring.cpp: No such file or directory
> sed: can't read ../base/source/timer.cpp: No such file or directory
> sed: can't read ../base/source/timer.cpp: No such file or directory
> sed: can't read ../pluginterfaces/base/funknown.cpp: No such file or directory
> sed: can't read ../pluginterfaces/base/funknown.cpp: No such file or directory
> sed: can't read ../pluginterfaces/base/ustring.cpp: No such file or directory
> sed: can't read ../public.sdk/source/common/openurl.cpp: No such file or directory
> sed: can't read ../public.sdk/source/common/openurl.cpp: No such file or directory
> sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
> sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
> sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
> sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
> sed: can't read ../public.sdk/source/common/threadchecker_win32.cpp: No such file or directory                                                                                               
> sed: can't read ../CMakeLists.txt: No such file or directory                                                                                                                                 
> mkdir: cannot create directory ‘../build’: File exists                                                                                                                                       
> CMake Error: The source directory "/home/b/Documents" does not appear to contain CMakeLists.txt.                                                                                             
> Specify --help for usage, or press the help button on the CMake GUI.                                                                                                                         
> ./lin-patchwin: 37: cd: can't cd to ./base                                                                                                                                                   
> make[1]: Entering directory '/home/b/Documents/build'                                                                                                                                        
> make[1]: *** No targets specified and no makefile found.  Stop.                                                                                                                              
> make[1]: Leaving directory '/home/b/Documents/build'
> ./lin-patchwin: 39: cd: can't cd to ../public.sdk
> make[1]: Entering directory '/home/b/Documents/build'
> make[1]: *** No targets specified and no makefile found.  Stop.
> make[1]: Leaving directory '/home/b/Documents/build'
> make: *** [Makefile:47: do_script2] Error 2

Not sure what I need to do to get this working to use vst3s in Reaper.

**Comment by ShortAce** [comment]
I got nearly the same error:
```
y4n@y4n-20245:~/Sources/LinVst3$ make
./lin-patchwin
sed: can't read ../public.sdk/source/common/systemclipboard_win32.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/fplatform.h: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/timer.cpp: No such file or directory
sed: can't read ../base/source/timer.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/funknown.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/funknown.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/ustring.cpp: No such file or directory
sed: can't read ../public.sdk/source/common/openurl.cpp: No such file or directory
sed: can't read ../public.sdk/source/common/openurl.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/common/threadchecker_win32.cpp: No such file or directory
sed: can't read ../CMakeLists.txt: No such file or directory
mkdir: cannot create directory ‘../build’: File exists
./lin-patchwin: 36: cmake: not found
./lin-patchwin: 37: cd: can't cd to ./base
make[1]: Entering directory '/home/y4n/Sources/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/y4n/Sources/build'
./lin-patchwin: 39: cd: can't cd to ../public.sdk
make[1]: Entering directory '/home/y4n/Sources/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/y4n/Sources/build'
make: *** [Makefile:47: do_script2] Error 2

```

**Comment by osxmidi** [comment]
The Makefile is set up for https://download.steinberg.net/sdk_downloads/vst-sdk_3.7.1_build-50_2020-11-17.zip

Download the file above and unzip it.

Unzip the LinVst3 source file (which will unzip a LinVst3 source folder).

The LinVst3 source folder needs to be placed within the VST3 SDK main folder (the VST3_SDK folder or the VST3 folder that contains the base, public.sdk, pluginterfaces etc folders) ie the LinVst3 source folder needs to be placed alongside the base, public.sdk, pluginterfaces etc folders of the VST3 SDK.

Then change into the LinVst3 source folder and run make and then sudo make install

---------

Assuming that your system has all of the libraries that are needed, which are listed in the LinVst3 Readme.

**Comment by osxmidi** [comment]
There are LinVst3 pre made binaries on the Releases page as well, that should work with most systems.
