### ISSUE TITLE
Lagging on changing presets and turning knobs

### ISSUE THREAD

**Issue by avanzzzi** [osxmidi/LinVst3#18]
After the update (4.7 -> 4.7.1) some plugins started to lag after preset changes and while turning knobs.

* Neural DSP Archetype Nolly (preset changes take 1-2 secs freeze)
* Nembrini Audio BST100 v2  (knobs freezing while turning)

I did a downgrade to 4.7 and all came back to normal.

After the upgrade/downgrade all the files from linvst3 was upgraded in the system and all plugins was converted pointing to the new linvst3.so and scanned again in the DAW (tested in Ardour and Reaper).

Wine-7.0

**Comment by osxmidi** [comment]
> After the update (4.7 -> 4.7.1) some plugins started to lag after preset changes and while turning knobs.
> 
>     * Neural DSP Archetype Nolly (preset changes take 1-2 secs freeze)
> 
>     * Nembrini Audio BST100 v2  (knobs freezing while turning)
> 
> 
> I did a downgrade to 4.7 and all came back to normal.
> 
> After the upgrade/downgrade all the files from linvst3 was upgraded in the system and all plugins was converted pointing to the new linvst3.so and scanned again in the DAW (tested in Ardour and Reaper).
> 
> Wine-7.0

Thanks, I'll look into it.

**Comment by osxmidi** [comment]
> After the update (4.7 -> 4.7.1) some plugins started to lag after preset changes and while turning knobs.
> 
>     * Neural DSP Archetype Nolly (preset changes take 1-2 secs freeze)
> 
>     * Nembrini Audio BST100 v2  (knobs freezing while turning)
> 
> 
> I did a downgrade to 4.7 and all came back to normal.
> 
> After the upgrade/downgrade all the files from linvst3 was upgraded in the system and all plugins was converted pointing to the new linvst3.so and scanned again in the DAW (tested in Ardour and Reaper).
> 
> Wine-7.0

I had a bug in the parameters.

I'll update it to LinVst3 4.7.2.
