### ISSUE TITLE
Suggestion to improve the file selection operation

### ISSUE THREAD

**Issue by ghost** [osxmidi/LinVst3#2]
Hi,

The file selection operation is not user frendly.... For example:

1.If the files .vst3 are cataloged in some sub-directory, I need to generate the .so file for each sub-directory. It's possible to select only the root of .vst3 files and then generate the .so for each?
2.I need to select the .so3 file for each .vst3 new directory and sub-directory: but the link to this file remain this for all the operations. It's possible to link only one time the .so3 file?

Thanks....

**Comment by osxmidi** [comment]
linvst3convert only does one directory.

linvst3converttree does sub directories as well.

**Comment by ghost** [comment]
Thanks... Thanks... Thanks....
