### ISSUE TITLE
Fail to build: libsdk_hosting.a not found

### ISSUE THREAD

**Issue by ycollet** [osxmidi/LinVst3#20]
I am trying to build LinVst3 on Fedora 38 with gcc-13.1 and wine-8.13.
I met a link error problem at the end of the build:
```
wineg++ -Wl,--subsystem,windows  lin-vst-server.wine.o remotepluginserver.wine.o paths.wine.o memorystream.wine.o basewrapper.wine.o ../build/lib/Release/libsdk_hosting.a ../build/lib/Release/libbase.a ../build/lib/Release/libpluginterfaces.a ../build/lib/Release/libsdk.a -L/opt/wine-stable/lib64/wine -L/opt/wine-devel/lib64/wine -L/opt/wine-staging/lib64/wine -L/opt/wine-stable/lib64/wine/x86_64-unix -L/opt/wine-devel/lib64/wine/x86_64-unix -L/opt/wine-staging/lib64/wine/x86_64-unix -L/usr/lib/x86_64-linux-gnu/wine-development -lpthread -lX11 -lshell32 -lole32 -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  -o lin-vst3-server.exe
winegcc: File does not exist: ../build/lib/Release/libsdk_hosting.a
make: *** [Makefile:54: lin-vst3-server.exe] Error 2
```

**Comment by osxmidi** [comment]
> I am trying to build LinVst3 on Fedora 38 with gcc-13.1 and wine-8.13. I met a link error problem at the end of the build:
> 
> ```
> wineg++ -Wl,--subsystem,windows  lin-vst-server.wine.o remotepluginserver.wine.o paths.wine.o memorystream.wine.o basewrapper.wine.o ../build/lib/Release/libsdk_hosting.a ../build/lib/Release/libbase.a ../build/lib/Release/libpluginterfaces.a ../build/lib/Release/libsdk.a -L/opt/wine-stable/lib64/wine -L/opt/wine-devel/lib64/wine -L/opt/wine-staging/lib64/wine -L/opt/wine-stable/lib64/wine/x86_64-unix -L/opt/wine-devel/lib64/wine/x86_64-unix -L/opt/wine-staging/lib64/wine/x86_64-unix -L/usr/lib/x86_64-linux-gnu/wine-development -lpthread -lX11 -lshell32 -lole32 -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  -o lin-vst3-server.exe
> winegcc: File does not exist: ../build/lib/Release/libsdk_hosting.a
> make: *** [Makefile:54: lin-vst3-server.exe] Error 2
> ```

Cmake wasn't picking up where ar was, so I changed some code and it seems to work.

I made this Fedora-38 version 
[LinVst3-4.9-Fedora-38.zip](https://github.com/osxmidi/LinVst3/files/12419139/LinVst3-4.9-Fedora-38.zip)

**Comment by ycollet** [comment]
Thanks a lot for the fix !
