### ISSUE TITLE
LinVST3 crash when I open the advanced controls window with Arturia demo plugins 

### ISSUE THREAD

**Issue by ghost** [osxmidi/LinVst3#3]
Linux Mint Cinnamom x64, 4.15.0-65-lowlatency, Reaper 5.985, Wine 4.20, LinVst3-1.7.1-Debian-Stretch

Hi,

when I open the advanced controls window with any Arturia demo plugins, and change some settings, after a while the audio stops in an infinite loop, crashing Reaper and Jack audio server. I need to restart my PC. One Program Error message is appear..

https://imgur.com/EeGStGE

Is there a way to fix this problem?

Thanks....

**Comment by osxmidi** [comment]
It seems to be some sort of Wine vcruntime problem.

I don't know if there is much that can be done. 

Maybe try winetricks vcrun2017

and try some dll overloads based on what dlls the vst3 uses like

 strings "/home/user/.wine/drive_c/Program Files/Common Files/VST3/DX7 V.vst3" | grep -i dll

/libsndfile-2.dll
./libsndfile-2.dll
x64/libsndfile-2.dll
.dll
SHCore.dll
user32.dll
ntdll
ExitDll
InitDll
WS2_32.dll
UxTheme.dll
KERNEL32.dll
USER32.dll
GDI32.dll
SHELL32.dll
ole32.dll
OLEAUT32.dll
COMDLG32.dll
ADVAPI32.dll
MSVCP140.dll
SHLWAPI.dll
WINMM.dll
IMM32.dll
OPENGL32.dll
VCRUNTIME140.dll
_seh_filter_dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
%s.dll

**Comment by gabriel-ales** [comment]
I could solve it by downloading and installing staging version 5.15 and setting in winecfg inside staging tab the following:
uncheck enable csmt
check enable gtk3 theming.
give it a try!
