### ISSUE TITLE
Error during make: processthreadapi.h

### ISSUE THREAD

**Issue by Goli4thus** [osxmidi/LinVst3#4]
Hi osxmidi!
I'm trying to build LinVst3 as described in the README:

1. download Vst3-SDK (steinberg website)
2. extract and place LinVst3 folder (latest release: 1.8) in that folder alongside "base", "public.sdk",...
3. run 'make'

And ends in an error with the following output:
`[ 42%] Linking CXX static library ../lib/Release/libpluginterfaces.a
make[3]: Leaving directory '/home/goli/Build/VST_SDK/VST3_SDK/build'
[ 42%] Built target pluginterfaces
make[3]: Entering directory '/home/goli/Build/VST_SDK/VST3_SDK/build'
Scanning dependencies of target sdk
make[3]: Leaving directory '/home/goli/Build/VST_SDK/VST3_SDK/build'
make[3]: Entering directory '/home/goli/Build/VST_SDK/VST3_SDK/build'
[ 42%] Building CXX object public.sdk/CMakeFiles/sdk.dir/source/common/commoniids.cpp.o
[ 57%] Building CXX object public.sdk/CMakeFiles/sdk.dir/source/common/pluginview.cpp.o
[ 57%] Building CXX object public.sdk/CMakeFiles/sdk.dir/source/common/threadchecker_linux.cpp.o
[ 57%] Building CXX object public.sdk/CMakeFiles/sdk.dir/source/common/threadchecker_win32.cpp.o
/home/goli/Build/VST_SDK/VST3_SDK/public.sdk/source/common/threadchecker_win32.cpp:42:10: fatal error: processthreadsapi.h: No such file or directory
   42 | #include <processthreadsapi.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
winegcc: g++ failed
make[3]: *** [public.sdk/CMakeFiles/sdk.dir/build.make:102: public.sdk/CMakeFiles/sdk.dir/source/common/threadchecker_win32.cpp.o] Error 2
make[3]: Leaving directory '/home/goli/Build/VST_SDK/VST3_SDK/build'
make[2]: *** [CMakeFiles/Makefile2:1061: public.sdk/CMakeFiles/sdk.dir/all] Error 2
make[2]: Leaving directory '/home/goli/Build/VST_SDK/VST3_SDK/build'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/home/goli/Build/VST_SDK/VST3_SDK/build/public.sdk'
make: *** [Makefile:47: do_script2] Error 2
`

Am I missing something? 
After some searches it looks like _processthreadsapi.h_ is included in _./public.sdk/source/common/threadchecker_win32.cpp_. Am I supposed to have that header on a linux system (Manjaro - stable) or should _threadchecker_win32.cpp_ not even be looked at while compiling on linux?

In your README you say _Currently builds ok with the vstsdk3613_08_04_2019_build_81_.
The latest version seems to be _vst-sdk_3.6.14_build-24_2019-11-29_.
Is it still working for you?

Sidenote: I've checked all the mentioned packages as far as I could (some guesses on what they are called on Manjaro). But overall it seemed ok.

**Comment by osxmidi** [comment]
Looks like Steinberg have updated the VST3 SDK.

For now the vstsdk3613_08_04_2019_build_81 SDK can be downloaded at https://download.steinberg.net/sdk_downloads/vstsdk3613_08_04_2019_build_81.zip

**Comment by osxmidi** [comment]
I've fixed it for the latest VST3 SDK vst-sdk_3.6.14_build-24_2019-11-29

**Comment by Goli4thus** [comment]
Alright, using _vstsdk3613_08_04_2019_build_81_ LinVst3 did in fact compile just fine before your latest commits.
Using latest LinVst3 version (repo master) in conjunction with _vst-sdk_3.6.14_build-24_2019-11-29_ compiles now as well.
Thanks for that!
