### ISSUE TITLE
Compiling TestVst3: How?

### ISSUE THREAD

**Issue by Goli4thus** [osxmidi/LinVst3#5]
(low prio)
I just tried to compile the TestVst3 utility after https://github.com/osxmidi/LinVst3/issues/4 had been fixed.

I assume (couldn't find any documentation that states otherwise) it's just a matter of changing into the _TestVst3_ folder and calling _make_.
This gives me the following:
`./lin-patchwin
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/fstring.cpp: No such file or directory
sed: can't read ../base/source/timer.cpp: No such file or directory
sed: can't read ../base/source/timer.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/funknown.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/funknown.cpp: No such file or directory
sed: can't read ../pluginterfaces/base/ustring.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../public.sdk/source/vst/vstparameters.cpp: No such file or directory
sed: can't read ../CMakeLists.txt: No such file or directory
CMake Error: The source directory "/home/goli/Build/VST_SDK_3614_newer/VST3_SDK/LinVst3-git" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
./lin-patchwin: line 28: cd: ./base: No such file or directory
make[1]: Entering directory '/home/goli/Build/VST_SDK_3614_newer/VST3_SDK/LinVst3-git/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/goli/Build/VST_SDK_3614_newer/VST3_SDK/LinVst3-git/build'
./lin-patchwin: line 30: cd: ../public.sdk: No such file or directory
make[1]: Entering directory '/home/goli/Build/VST_SDK_3614_newer/VST3_SDK/LinVst3-git/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/goli/Build/VST_SDK_3614_newer/VST3_SDK/LinVst3-git/build'
make: *** [Makefile:39: do_script2] Error 2
`

Am I doing something wrong?

**Comment by osxmidi** [comment]
It's the same as for LinVst3.

I've added a howto make section to the TestVst3 folders readme.

To make

This TestVst3 source folder needs to be placed within the VST3 SDK main folder (the VST3_SDK folder or the VST3 folder that contains the base, public.sdk, pluginterfaces etc folders) ie the TestVst3 source folder needs to be placed alongside the base, public.sdk, pluginterfaces etc folders of the VST3 SDK.

Then change into the TestVst3 folder and run make.

**Comment by Goli4thus** [comment]
Ah, that explains it. Compiles just fine now. Thanks!
