### ISSUE TITLE
Linvst3 and Melodyne Essential 5

### ISSUE THREAD

**Issue by MosesKim84** [osxmidi/LinVst3#9]
Hello, I followed the instructions but when the linvst3 server started working on the plugin during startup scan of Reaper 6 (native Linux) it crashed with the following log file: 

[LinVST3_melodyne.txt](https://github.com/osxmidi/LinVst3/files/5270529/LinVST3_melodyne.txt)

Can anyone point me into the right direction to help get this error fixed? This is the first VST3 plugin I've tried to use with reaper. I have successfully been able to get Ozone 9, Neutron 9 and Nectar 3 to work with Reaper in VST2 formats with linvst. Thanks!

**Comment by osxmidi** [comment]
> Hello, I followed the instructions but when the linvst3 server started working on the plugin during startup scan of Reaper 6 (native Linux) it crashed with the following log file:
> 
> [LinVST3_melodyne.txt](https://github.com/osxmidi/LinVst3/files/5270529/LinVST3_melodyne.txt)
> 
> Can anyone point me into the right direction to help get this error fixed? This is the first VST3 plugin I've tried to use with reaper. I have successfully been able to get Ozone 9, Neutron 9 and Nectar 3 to work with Reaper in VST2 formats with linvst. Thanks!

It looks like that vst3 is a 32 bit vst3.

LinVst3 only handles 64 bit vst3's.

Also, using testvst3.exe is a way to test whether or not a vst3 is likely to run ok.

There is also testvst.exe for LinVst and vst2's.

**Comment by osxmidi** [comment]
> Hello, I followed the instructions but when the linvst3 server started working on the plugin during startup scan of Reaper 6 (native Linux) it crashed with the following log file:
> 
> [LinVST3_melodyne.txt](https://github.com/osxmidi/LinVst3/files/5270529/LinVST3_melodyne.txt)
> 
> Can anyone point me into the right direction to help get this error fixed? This is the first VST3 plugin I've tried to use with reaper. I have successfully been able to get Ozone 9, Neutron 9 and Nectar 3 to work with Reaper in VST2 formats with linvst. Thanks!

There is an unimplemented (missing) function in the error log.

I can't make out the function name.

A dll override can help with unimplemented function errors.

It might be a good idea to use winetricks to install the vcrun dll's.

"winetricks -q vcrun2015"
